### ISSUE TITLE
Images aren't showing up on heroku

### ISSUE THREAD

**Issue by veracl** [veracl/recipes#3]

**Comment by roschaefer** [comment]
Steps to reproduce:
1. Deploy on heroku
2. Run seed data
3. Visit the app

**Comment by roschaefer** [comment]
Glad you figured it out - is it not possible to upload images on heroku? Link?

**Comment by veracl** [comment]
No, I couldn't get it to work, and it's apparently not recommended anyways:

http://stackoverflow.com/questions/24642967/can-i-host-images-in-heroku-or-do-i-need-s3

> The short answer: if you allow users or admins to upload images, you should not use Heroku's file system for this as the images will suddenly vanish.
> 
> As explained in the [Heroku documentation](https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem):
> 
> > Each dyno gets its own ephemeral filesystem, with a fresh copy of the most recently deployed code. During the dyno’s lifetime its running processes can use the filesystem as a temporary scratchpad, but no files that are written are visible to processes in any other dyno and any files written will be discarded the moment the dyno is stopped or restarted.
